### PR TITLE
added switch to toolbox categories, refactored search filter code

### PR DESCRIPTION
**Pull request by chensation**

### CODE REVIEW

**Comment by syuChen1** [comment]
- I think this part needs some alignment. 

image

- For the block filter, I think it would be better if it displays all the blocks based on the result of the search instead of displaying categories where you have to click on one to find the block you want. 
- Lastly for the ```Select All``` button, it still displays selected when you un-select a block or categories of blocks. It would be nice to have another condition where when ```Select All``` is on and you check off a block, the ```Select All``` will be automatically checked off.

**Comment by syuChen1** [comment]
Nicely done. I found a few more bugs tho.

- [ ] In content creator view, the screen looks like this when I have a 1440p screen. It also happens in student view. 

image

- [ ] When click ```select all``` on a filtered condition, it should only select the blocks that matched and should not select the ```select category``` switch of other categories.

image

- [ ] When clearing filter conditions, all the categories expand out. Would be nice to have them all closed. 
- [ ] Compiling code need some top margin
image

**Comment by chensation** [comment]
> * [ ]  In content creator view, the screen looks like this when I have a 1440p screen. It also happens in student view.  

 cannot be reproduced, did you refresh the window after changing the display resolution?
I have some questions about the other changes requested, I will save it for the meeting.

**Comment by chensation** [comment]
- [ ] Fix top menu on smaller screens
- [ ] Select all and select category should not be affected by the search filter
- [ ] Unchecking a checkbox should also uncheck select all and select category
- [ ] Disable select all and select category if there’s a search filter
- [ ] Search only open / close categories with valid items in it
- [ ] Categories with selected items in them should remain open

**Review by syuChen1 — APPROVED** [review]

**Pull request merged**
